site_name: Nexus Gourmet
nav:
  - Início: index.md
  - Documento de Visão: visão.md
  - Documento de Arquitetura: arquitetura.md
  - Política de Branches e Commits: politica-commits.md
  - Relatório de Métricas: metricas.md
theme:
  name: material
  logo: logo.png                  
  favicon: logo.png                
  palette:
    - scheme: default
      primary: custom               
      accent: custom
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest

extra_css:
  - css/extra.css